version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: loan_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: loan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: loan_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgrespassword@db:5432/loan_db
      PORT: 8000
      HOST: 0.0.0.0
      LOW_RISK_THRESHOLD: 0.30
      HIGH_RISK_THRESHOLD: 0.60
      ACTIVE_MODEL: XGBoost
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./models:/app/models
      - ./data:/app/data

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: loan_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
